apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-service
  namespace: production
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend-prod
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: frontend.aditia701.xyz
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: frontend-prod-service
            port: 
              number: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod
  namespace: production
spec:
  selector:
    matchLabels:
      app: frontend-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-prod
    spec:
      containers:
        - name: frontend-prod
          image: aditiaipr/frontend:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 700m
              memory: 800Mi
            requests:
              cpu: 200m
              memory: 400Mi
      
